### PR TITLE
MARP-626 Fix for Dev Fail on Market-Monitor

### PR DESCRIPTION
**Pull request by phhung-axonivy**

### CODE REVIEW

**Comment by ivy-rew** [comment]
looks like we must 'enableWebServer=true' for the failing test

**Comment by phhung-axonivy** [comment]
> looks like we must 'enableWebServer=true' for the failing test

Hi @ivy-rew 
I added 'enableWebServer=true' but the test still fails. I report this issue to @nqhoan-axonivy and he will check it later.

**Comment by ivy-rew** [comment]
> > looks like we must 'enableWebServer=true' for the failing test
> 
> Hi @ivy-rew I added 'enableWebServer=true' but the test still fails. I report this issue to @nqhoan-axonivy and he will check it later.



Ok, I quickly checked the code; it seems as if the 'restClient' by name resolution is not wise, since it contains special characters.
I think you just have to change the test-setup to lookup the client by ID:
    UUID: c700c640-4f76-4cbe-8724-dbc663d8bc0a

https://github.com/axonivy-market/ui-path-connector/blob/ff9dcdba0b24e35b288aeea155b28d2a610bddaa/ui-path-connector-test/src_test/com/axonivy/connector/uipath/test/TestUiPathRPA.java#L38

**Comment by phhung-axonivy** [comment]
Hi @ivy-rew 
@nqhoan-axonivy fixed the test.
Could you please approve this PR?

**Review by nqhoan-axonivy — APPROVED** [review]
LGTM

**Comment by ivy-rew** [comment]
:trophy:

**Pull request merged**
